//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenguru_four_
{
    using System;
    using System.Collections.Generic;
    
    public partial class catigories
    {
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string name { get; set; }
    }
}
