//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenguru_four_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kenguEntities : DbContext
    {
        public kenguEntities()
            : base("name=kenguEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<catigories> catigories { get; set; }
        public virtual DbSet<goods> goods { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<sellers> sellers { get; set; }
    }
}
