//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenguru_four_
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int id { get; set; }
        public Nullable<int> id_goods { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> status { get; set; }
        public string track { get; set; }
        public string adres { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    }
}
