//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenguru_four_
{
    using System;
    using System.Collections.Generic;
    
    public partial class sellers
    {
        public int id { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string name { get; set; }
        public string pasword { get; set; }
        public string phone { get; set; }
        public string adress { get; set; }
        public string description { get; set; }
    }
}
